###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: mysql:5.7
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_assinatura
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
        ports:
            - '54003:3306'

    webserver:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ./api:/application
            - ./devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '54002:80'

    php-fpm:
        build: devops/php-fpm
        working_dir: /application
        volumes:
            - ./api:/application
            - ./devops/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
